security:
  # Pas de "enable_authenticator_manager" en Symfony 7

  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api/v1
      stateless: true
      provider: app_user_provider
      jwt: ~   # Authenticator Lexik

  access_control:
    - { path: ^/api/v1/auth/(login|register)$, roles: PUBLIC_ACCESS }
    - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }